eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
  instance:
      prefer-ip-address: true
server:
  port: 5000
spring:
  application:
    name: zuulserver
zuul:
  routes:
    plat:
      path: /plat/**
      serviceId: plat-service
  ignored-services: '*'
  prefix: /services