server:
  port: 3000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
  instance:
      prefer-ip-address: true
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ysjava007/xigou-configserver.git
          username: ysjava007
          password: Yinshuai123